export default [
    {
        "country": "AD",
        "hot dog": 97,
        "burger": 103,
        "sandwich": 86,
        "kebab": 117,
        "fries": 44,
        "donut": 49,
    },
    {
        "country": "AE",
        "hot dog": 45,
        "burger": 130,
        "sandwich": 95,
        "kebab": 183,
        "fries": 33,
        "donut": 89,
    },
    {
        "country": "AF",
        "hot dog": 56,
        "burger": 157,
        "sandwich": 175,
        "kebab": 130,
        "fries": 173,
        "donut": 37,
    },
    {
        "country": "AG",
        "hot dog": 19,
        "burger": 75,
        "sandwich": 101,
        "kebab": 191,
        "fries": 104,
        "donut": 101,
    },
    {
        "country": "AI",
        "hot dog": 181,
        "burger": 6,
        "sandwich": 154,
        "kebab": 152,
        "fries": 158,
        "donut": 27,
    },
    {
        "country": "AL",
        "hot dog": 88,
        "burger": 66,
        "sandwich": 139,
        "kebab": 151,
        "fries": 79,
        "donut": 138,
    },
    {
        "country": "AM",
        "hot dog": 109,
        "burger": 158,
        "sandwich": 150,
        "kebab": 155,
        "fries": 171,
        "donut": 112,
    }
]