// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:947d4aaf-30ef-457b-af42-76ec7a211057",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sSZLa32M7",
    "aws_user_pools_web_client_id": "790eq1nsibl1cgl7aj73qmoeao",
    "oauth": {}
};


export default awsmobile;
