// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3076ff8c-9193-4464-837c-66267a6a30a7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hxQ1cJ7rw",
    "aws_user_pools_web_client_id": "4cj44n9rp9qllp7c47b6appbn3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ftx4j2zh7rh4jdyahfc6s4p7iu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
